### ISSUE TITLE
 Array are not allowed in the global section

### ISSUE THREAD

**Issue by main1015** [bitnami/bitnami-docker-php-fpm#146] opened 2021-07-12 02:07 UTC
**Version**
7.4

**Description**

![image](https://user-images.githubusercontent.com/3272281/125220217-e95ec100-e2f8-11eb-90a4-64324070296f.png)

**Comment by migruiz4** [comment] 2021-07-12 15:21
Hi @main1015,

Could you please share more details about your case? Steps to reproduce, configuration files, or any additional information would be helpful.

**Comment by main1015** [comment] 2021-07-28 01:26
> This Issue has been automatically marked as "stale" because it has not had recent activity (for 15 days). It will be closed if no further activity occurs. Thanks for the feedback.

我就下载了一个这个镜像，然后run它就行了

**Comment by migruiz4** [comment] 2021-07-28 06:16
Hi @main1015,

I'm sorry but I need to ask you to continue this discussion in English.

---

The issue seems related to the content of `php-fpm.conf`, but the information is not enough to help us determine the root cause of the problem.

As I asked in my previous answer, it would be helpful if you could provide some steps to reproduce, including: 
- Method used (docker run, docker-compose, kubernetes...)
- Additional settings (environment variables, mounted configuration, etc.)
- Files that could help us reproduce the issue easily (docker-compose.yaml, kubernetes manifest or commands, if applicable).

That information may help us determine the root cause or the issue and find a solution.

**Comment by main1015** [comment] 2021-07-28 06:22
Hi @migruiz4 
Although I do technical, but I am not good English, I will describe the problem through the form of translation.
First I dropped this mirror via docker then ran via docker run the other instructions operations were not done and then the problem arises

**Comment by migruiz4** [comment] 2021-07-28 06:43
Using a translator is fine, no worries.

Could you please share the command you are using to run the container?

**Comment by main1015** [comment] 2021-07-28 06:47
`docker run --name phpfpm bitnami/php-fpm:7.4`

**Comment by migruiz4** [comment] 2021-07-28 13:54
Are you running `docker run` without any additional volume or configuration?

I'd recommend having a look at the following sections of the Readme:
- https://github.com/bitnami/bitnami-docker-php-fpm#php-runtime
- https://github.com/bitnami/bitnami-docker-php-fpm#running-your-php-script

**Comment by migruiz4** [comment] 2021-07-28 13:59
I tried to reproduce the issue, but the command `docker run --name phpfpm bitnami/php-fpm:7.4` runs fine and doesn't generate any output.

```
$ docker run -it --name phpfpm bitnami/php-fpm:7.4

```

The error log in the image your shared aims that something may be wrong inside `/opt/bitnami/php/etc/php-fpm.conf` or `/opt/bitnami/php/etc/php-fpm.d/*.conf`.

**Comment by migruiz4** [comment] 2021-07-28 14:03
Maybe I can not reproduce the issue because of some hardware differences. 

Is it possible that you are using an ARM CPU?

**Comment by main1015** [comment] 2021-07-29 01:41
@migruiz4 Has solved, should be the profile data volume, thank you for your help, thank you very much!

**Comment by migruiz4** [comment] 2021-07-29 06:17
That is great! I'm glad the issue has been solved.

I will then proceed to close this issue. Please let us know if you find any further issue.

**Closed by migruiz4** 2021-07-29 06:17 UTC
